### ISSUE TITLE
Module composition vs Information Routing

### ISSUE THREAD

**Issue by helenlu66** [ManifoldRG/AgentForge#14]
There are generally 3 approaches to how the controller interacts with modules as outlined in the conceptual overview below. We want to investigate the approaches others have taken and the pros & cons for each approach.
![image](https://github.com/ManifoldRG/AgentForge/assets/38745260/4225343d-36e4-4609-be72-f919dc59596f)

approach 1: controller does module composition and handles information flow similar to HuggingGPT. 
approach 2: human user does module composition but controller handles information flow similar to LangChain.
approach 3: module composition remains fixed and controller handles information flow.

output: 
a document outlining the details of common approaches (may or may not include the 3 approaches mentioned above) and listing the pros & cons for each approach

**Comment by helenlu66** [comment]
https://docs.google.com/document/d/1XrsW2wrymVa7PU4JJKQ2cJz_81IeJ8a04Y8pCmQMbKA/edit

**Comment by harshsikka** [comment]
I think this can be archived as it is somewhat out of date
