### ISSUE TITLE
AF use cases brainstorm

### ISSUE THREAD

**Issue by helenlu66** [ManifoldRG/AgentForge#15]
context: use cases largely determine the desired capabilities of AF that in turn inform design decisions. Currently, most use cases we've seen based on LangChain and HuggingGPT take language input from users since both use LLM as controllers. Since we aim to accommodate controllers that are not LLMs, the biggest uncertainty we face is: what input do we take from the user for a controller that's not a language model?

outcome: a document listing the use cases we want to cover for v0 with a focus on user input. The goal is to inform the design of a controller wrapper that accommodates all input modalities

**Comment by helenlu66** [comment]
[Use Cases](https://docs.google.com/document/d/1tr8EZ5JwlpqAfq2ROCxPp6W86iQYcpORutM_qfXXX3Y/edit) WIP

**Comment by harshsikka** [comment]
Related: #20
