### ISSUE TITLE
Literature Review Synopses

### ISSUE THREAD

**Issue by helenlu66** [ManifoldRG/AgentForge#22]
In preparation to write a survey paper on AI agents, summarize useful papers read in [Research Paper Synopses](https://docs.google.com/document/d/1p6kzktsZo0ooKW3GdgxJxE7ae9Mego6mksqfZWnl4lw/edit#heading=h.yw0a9fpw8fzc). This issue can be broken down into smaller issues where each issue corresponds with a research paper

**Comment by harshsikka** [comment]
out of date
