### ISSUE TITLE
Investigate and Demo how Langchain approaches building Agents

### ISSUE THREAD

**Issue by harshsikka** [ManifoldRG/AgentForge#5]
Context: we want to understand different approaches/methodologies to building "agents". Langchain builds LLM based agents, we want to understand their approach.

Output: Prepare an overview of the [Langchain](https://github.com/hwchase17/langchain) approach to building Agents, and build/demo a basic agent.

**Comment by harshsikka** [comment]
@bfaught3 Helen was going to work with you on this, I think we're still trying to figure out how to add her to GH. Worth reaching out to her to coordinate, perhaps over discord.

**Comment by helenlu66** [comment]
presentation on LangChain [here](https://docs.google.com/presentation/d/1WTChecnPPrOXI-83ma97eWPtl2IPtYpUy4KDrqjgwXk/edit?usp=sharing)

**Comment by harshsikka** [comment]
@helenlu66 I totally forgot to comment this a few days ago, but would be useful to capture even small tasks like this as their own issues

**Comment by harshsikka** [comment]
https://github.com/ManifoldRG/AgentForge/issues/5#issuecomment-1566182732

Calling the above out again, would be good to understand each separate thrust in its own issue.

**Comment by helenlu66** [comment]
closing this for now since the to-do items are completed. We can re-open later if we decide to look more into LangChain
