### ISSUE TITLE
Investigate and Demo HF Transformer Agents

### ISSUE THREAD

**Issue by harshsikka** [ManifoldRG/AgentForge#6]
Context: we want to understand different approaches/methodologies to building "agents". Huggingface has recently added abstractions to build agents in their transformers library, we want to understand their approach.

Output: Prepare an overview of the [HF Agents](https://huggingface.co/docs/transformers/transformers_agents) approach to building Agents, and build/demo a basic agent. To be shared with the team.

**Comment by KrnTneja** [comment]
Slides on HuggingFace GPT: https://docs.google.com/presentation/d/1H2KAepo72ZqAx5wIdc4N7cNLWtkB1uzJdetaPGju670/edit?usp=drive_link
Presented them to in the group meeting on June 4, 2023.
