### ISSUE TITLE
Update AF Target/Desired Capabilities Document

### ISSUE THREAD

**Issue by harshsikka** [ManifoldRG/AgentForge#9]
@helenlu66 put together https://docs.google.com/document/d/1sjZGct_GtT7n0DmMeVG-8V6HBMv2X9nop5O-clpbnWc/edit?usp=sharing, outlining some example desired capabilities

We should outline the full spectrum of target capabilities for AF, and then bucket them into "versions" that prioritize key features/interaction patterns, which then can be used to inform our experimental roadmap for summer 2023 and beyond. 

Outcome: updated desired capabilities document by 06/25

**Comment by harshsikka** [comment]
Also, I suspect this will evolve over time. But we want to now iterate rapidly towards a v0 for the summer.

**Comment by helenlu66** [comment]
added "input & output parsers" and "success metrics" as desired capabilities for v0

**Comment by harshsikka** [comment]
@helenlu66 I moved this to blocked because we're basically reviewing how we think about agents, which will of course influence how we think about desired capabilities

**Comment by harshsikka** [comment]
Project has moved on from this
